Controllers/ProduktyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InStock.Database;
using System.Data;
using Microsoft.EntityFrameworkCore;

namespace InStock.Controllers
{
    public class ProduktyController : Controller
    {
        private InStockDatabase database;
        private ManagerPowiadomien managerPowiadomien;
        private SprawdzaniePowiadomien sprawdzaniePowiadomien;
        public ProduktyController(InStockDatabase db, ManagerPowiadomien managerPowiadomien, SprawdzaniePowiadomien sprawdzaniePowiadomien)
        {
            this.database = db;
            this.managerPowiadomien = managerPowiadomien;
            this.sprawdzaniePowiadomien = sprawdzaniePowiadomien;
        }
        public IActionResult Index()
        {
            var lista = this.database.Produkty.OrderBy(x => x.ProduktId).ToList();
            return View(lista);
        }

        public IActionResult Dodaj()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Dodaj(Produkt nowyProdukt)
        {
            this.database.Produkty.Add(nowyProdukt);
            this.database.SaveChanges();

            sprawdzaniePowiadomien.CzyBrakuje(nowyProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XS);
            sprawdzaniePowiadomien.CzyBrakuje(nowyProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.S);
            sprawdzaniePowiadomien.CzyBrakuje(nowyProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.M);
            sprawdzaniePowiadomien.CzyBrakuje(nowyProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.L);
            sprawdzaniePowiadomien.CzyBrakuje(nowyProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XL);
            return RedirectToAction("Index");
        }

        public IActionResult Usun(int id)
        {
            var usuniety = this.database.Produkty.FirstOrDefault(x => x.ProduktId.Equals(id));
            var stanSklepu = this.database.StanSklepu.FirstOrDefault(x => x.ProduktId.Equals(id));
            if (usuniety != null)
            {
                this.database.Produkty.Remove(usuniety);
                this.database.StanSklepu.Remove(stanSklepu);
                this.database.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Edycja(int id)
        {
            var edytowany = this.database.Produkty.FirstOrDefault(x => x.ProduktId.Equals(id));
            if (edytowany == null)
            {
                return RedirectToAction("Index");
            }

            return View(edytowany);
        }

        [HttpPost]
        public IActionResult Edycja(Produkt produkt)
        {
            var dbProdukt = this.database.Produkty.FirstOrDefault(x => x.ProduktId.Equals(produkt.ProduktId));
            if (dbProdukt != null)
            {
                dbProdukt.Kod = produkt.Kod;
                dbProdukt.Nazwa = produkt.Nazwa;
                dbProdukt.RozmiarXS = produkt.RozmiarXS;
                dbProdukt.RozmiarS = produkt.RozmiarS;
                dbProdukt.RozmiarM = produkt.RozmiarM;
                dbProdukt.RozmiarL = produkt.RozmiarL;
                dbProdukt.RozmiarXL = produkt.RozmiarXL;
                dbProdukt.Cena = produkt.Cena;



                this.database.SaveChanges();

                sprawdzaniePowiadomien.CzyBrakuje(dbProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XS);
                sprawdzaniePowiadomien.CzyBrakuje(dbProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.S);
                sprawdzaniePowiadomien.CzyBrakuje(dbProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.M);
                sprawdzaniePowiadomien.CzyBrakuje(dbProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.L);
                sprawdzaniePowiadomien.CzyBrakuje(dbProdukt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XL);

            }

            return RedirectToAction("Index");
        }

    }
}

Controllers/SklepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InStock.Database;
using Microsoft.EntityFrameworkCore;

namespace InStock.Controllers
{
    public class SklepController : Controller
    {
        private InStockDatabase database;
        private ManagerPowiadomien managerPowiadomien;
        private SprawdzaniePowiadomien sprawdzaniePowiadomien;
        public SklepController(InStockDatabase db, ManagerPowiadomien managerPowiadomien, SprawdzaniePowiadomien sprawdzaniePowiadomien)
        {
            this.database = db;
            this.managerPowiadomien = managerPowiadomien;
            this.sprawdzaniePowiadomien = sprawdzaniePowiadomien;
        }
        public IActionResult Index()
        {
            var model = this.database.StanSklepu.Include(x => x.Produkt).ToList();
            return View(model);
        }

        public IActionResult Przenies(int id)
        {
            var produkt = this.database.Produkty.FirstOrDefault(x => x.ProduktId.Equals(id));
            if (produkt != null)
            {
                return View(produkt);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Przenies(Przeniesienie przeniesienie)
        {
            var produkt = this.database.Produkty.FirstOrDefault(x => x.ProduktId.Equals(przeniesienie.ProduktId));
            if (produkt == null)
            {
                return RedirectToAction("Index");
            }
            przeniesienie.PobierzBledy(produkt).ForEach(x => { ModelState.AddModelError("", x); });
            if (!ModelState.IsValid)
            {
                return View(produkt);
            }
            produkt.OdejmijStan(przeniesienie);

            sprawdzaniePowiadomien.CzyBrakuje(produkt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XS);
            sprawdzaniePowiadomien.CzyBrakuje(produkt.ProduktId, SprawdzaniePowiadomien.Rozmiar.S);
            sprawdzaniePowiadomien.CzyBrakuje(produkt.ProduktId, SprawdzaniePowiadomien.Rozmiar.M);
            sprawdzaniePowiadomien.CzyBrakuje(produkt.ProduktId, SprawdzaniePowiadomien.Rozmiar.L);
            sprawdzaniePowiadomien.CzyBrakuje(produkt.ProduktId, SprawdzaniePowiadomien.Rozmiar.XL);

            var stanSklepu = this.database.StanSklepu.FirstOrDefault(x => x.ProduktId.Equals(przeniesienie.ProduktId));
            if (stanSklepu == null)
            {
                stanSklepu = new StanSklepu();
                stanSklepu.ProduktId = przeniesienie.ProduktId;
                this.database.StanSklepu.Add(stanSklepu);
            }
            stanSklepu.DodajStan(przeniesienie);
            this.database.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Usun(int id)
        {
            var usuniety = this.database.StanSklepu.FirstOrDefault(x => x.StanSklepuId.Equals(id));
            if (usuniety != null)
            {
                this.database.StanSklepu.Remove(usuniety);
                this.database.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/SprzedazController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InStock.Database;
using Microsoft.EntityFrameworkCore;


namespace InStock.Controllers
{
    public class SprzedazController : Controller
    {
        private InStockDatabase database;
        private ManagerPowiadomien managerPowiadomien;
        private SprawdzaniePowiadomien sprawdzaniePowiadomien;
        public SprzedazController(InStockDatabase db, ManagerPowiadomien managerPowiadomien, SprawdzaniePowiadomien sprawdzaniePowiadomien)
        {
            this.database = db;
            this.managerPowiadomien = managerPowiadomien;
            this.sprawdzaniePowiadomien = sprawdzaniePowiadomien;
        }

        public IActionResult Index()
        {
            var model = this.database.Sprzedaz.Include(x => x.Produkt).OrderByDescending(x => x.Data).ToList();
            return View(model);
        }

        public IActionResult Sprzedaj(int id)
        {
            var sprzedany = this.database.StanSklepu.FirstOrDefault(x => x.StanSklepuId.Equals(id));
            if (sprzedany == null)
            {
                return RedirectToAction("Index");
            }
            return View(sprzedany);
        }

        [HttpPost]
        public IActionResult Sprzedaj(Sprzedaz sprzedawanie)
        {
            var stanSklepu = this.database.StanSklepu.Include(x => x.Produkt).FirstOrDefault(x => x.StanSklepuId.Equals(sprzedawanie.StanSklepuId));
            if (stanSklepu == null)
            {
                return RedirectToAction("Index");
            }
            sprzedawanie.PokazRozmiary(stanSklepu).ForEach(x => { ModelState.AddModelError("", x); });

            if (!ModelState.IsValid)
            {
                return View(stanSklepu);
            }
            stanSklepu.OdejmijStan(sprzedawanie);
            sprzedawanie.Data = DateTime.Now;
            this.database.Sprzedaz.Add(sprzedawanie);
            this.database.SaveChanges();

            sprawdzaniePowiadomien.JakSieSprzedaje(stanSklepu.ProduktId);

            sprawdzaniePowiadomien.CzyBrakujeNaSklepie(stanSklepu.ProduktId, SprawdzaniePowiadomien.Rozmiar.XS);
            sprawdzaniePowiadomien.CzyBrakujeNaSklepie(stanSklepu.ProduktId, SprawdzaniePowiadomien.Rozmiar.S);
            sprawdzaniePowiadomien.CzyBrakujeNaSklepie(stanSklepu.ProduktId, SprawdzaniePowiadomien.Rozmiar.M);
            sprawdzaniePowiadomien.CzyBrakujeNaSklepie(stanSklepu.ProduktId, SprawdzaniePowiadomien.Rozmiar.L);
            sprawdzaniePowiadomien.CzyBrakujeNaSklepie(stanSklepu.ProduktId, SprawdzaniePowiadomien.Rozmiar.XL);

            return RedirectToAction("Index");
        }

    }
}

Controllers/StatystykiController.cs
using Microsoft.AspNetCore.Mvc;
using InStock.Database;
using System.Linq;
using InStock.Models;

namespace InStock.Controllers
{
    public class StatystykiController : Controller
    {
        private InStockDatabase database;
        private ManagerPowiadomien managerPowiadomien;
        public StatystykiController(InStockDatabase db, ManagerPowiadomien managerPowiadomien)
        {
            this.database = db;
            this.managerPowiadomien = managerPowiadomien;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SprzedazDnia()
        {
            var sprzedaze = this.database.Sprzedaz.ToList();
            var sprzedazdzienna = new SprzedazDzienna();
            var zmienna = sprzedazdzienna.SprawdzSprzedazDzienna(sprzedaze);
            return View(zmienna);
        }

        public IActionResult SprzedazRozmiarowek()
        {
            var sprzedaze = this.database.Sprzedaz.ToList();
            var sprzedazdzienna = new SprzedazDzienna();
            var rozmiar = sprzedazdzienna.SprawdzSprzedazRozmiarow(sprzedaze);   
            return View(rozmiar);
        }

        public IActionResult SprzedazMiesieczna()
        {
            var sprzedaze = this.database.Sprzedaz.ToList();
            var sprzedazmiesieczna = new SprzedazMiesieczna();
            var sprzedaneprodukty = sprzedazmiesieczna.SprawdzSprzedazMiesieczna(sprzedaze, database);
            return View(sprzedaneprodukty);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InStock</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container p-3 mb-2 bg-dark text-white">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">InStock</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse-right collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="Home" asp-action="Index">Strona
                                główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sklep" asp-action="Index">Stan
                                sklepowy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produkty" asp-action="Index">Stan
                                magazynowy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sprzedaz" asp-action="Index">Sprzedane</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Powiadomienia" asp-action="Index">Powiadomienia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Statystyki" asp-action="Index">Statystyki</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Zuzanna Wiśniewska - InStock
        </div>
    </footer>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/toastr/toastr.min.js"></script>
    <script src="/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>